name: proteus
channels:
  - conda-forge
dependencies:
  # Core Python
  - python=3.13
  - pip
  - pytest

  # Non-Python dependencies (system-level)
  - wget
  - make
  - gfortran
  - netcdf-fortran
  - git  # required for AGNI cloning if Git is not present
  # Python packages via pip
  - pip:
    - zenodo_client>=0.4.1
    - osfclient
