# PROTEUS configuration file (version 2.0)

version = "2.0"

# ----------------------------------------------------
# Parameters
[params]
    # output files
    [params.out]
        logging     = "DEBUG"
        path        = "toi6255b"
        plot_mod    = 5      # Plotting frequency, 0: wait until completion | n: every n iterations

# ----------------------------------------------------
# Star
[star]

    # Physical parameters
    mass    = 0.353      # M_sun
    age_ini = 0.100     # Gyr, model initialisation/start age

    module  = "mors"
    [star.mors]
        rot_pcntle = 40.0     # rotation percentile
        rot_period = "none"    # rotation period [days]
        tracks  = "spada" # evolution tracks: spada | baraffe
        age_now = 6    # Gyr, current age of star used for scaling
        spec    = "stellar_spectra/Named/gj176.txt" # stellar spectrum

# Orbital system
[orbit]
    semimajoraxis   = 0.0053    # AU
    eccentricity    = 0.0      # dimensionless
    zenith_angle    = 54.74     # degrees
    s0_factor       = 0.25      # dimensionless

    module  = "lovepy"
    [orbit.lovepy]
        visc_thresh = 1e9   # Minimum viscosity required for heating [Pa s]

# Planetary structure - physics table
[struct]
    radius_int  = 1.079       # R_earth
    corefrac    = 0.55      # non-dim., radius fraction

# Atmosphere - physics table
[atmos_clim]
    surface_d       = 0.01      # m, conductive skin thickness
    surface_k       = 2.0       # W m-1 K-1, conductive skin thermal conductivity
    surf_state      = "skin"    # surface scheme: "mixed_layer" | "fixed" | "skin"
    surf_greyalbedo = 0.2       # surface grey albedo
    rayleigh        = true      # Enable rayleigh scattering

    module  = "agni"           # Which atmosphere module to use

    [atmos_clim.agni]
        p_top           = 1.0e-5        # bar, top of atmosphere grid pressure
        spectral_group  = "Dayspring"   # which gas opacities to include
        spectral_bands  = "48"         # how many spectral bands?
        num_levels      = 40            # Number of atmospheric grid levels
        chemistry       = "none"        # "none" | "eq"
        surf_material   = "greybody"    # surface material file for scattering
        solve_energy    = true         # solve for energy-conserving atmosphere profile
        solution_atol   = 1e-2          # solver absolute tolerance
        solution_rtol   = 5e-2          # solver relative tolerance
        overlap_method    = "ee"          # gas overlap method
        condensation    = true          # volatile condensation
        real_gas        = true          # use real-gas equations of state

# Volatile escape - physics table
[escape]
    module = "none"    # Which escape module to use

# Interior - physics table
[interior]
    radiogenic_heat = true  # enable radiogenic heat production
    tidal_heat      = true  # enable tidal heat production

    module = "spider"   # Which interior module to use

    [interior.spider]
        num_levels               = 70       # Number of SPIDER grid levels
        mixing_length            = 2         # Mixing length parameterization
        tolerance                = 1.0e-8    # absolute solver tolerance
        tolerance_rel            = 1.0e-8    # relative solver tolerance
        solver_type              = "bdf"     # SUNDIALS solver method
        tsurf_atol               = 20.0      # tsurf_poststep_change
        tsurf_rtol               = 0.02      # tsurf_poststep_change_frac
        ini_entropy              = 3000.0    # Surface entropy conditions [J K-1 kg-1]
        ini_dsdr                 = -4.698e-6 # Interior entropy gradient [J K-1 kg-1 m-1]
        conduction               = true      # enable conductive heat transfer
        convection               = true      # enable convective heat transfer
        gravitational_separation = true      # enable gravitational separation
        mixing                   = true      # enable mixing
        matprop_smooth_width     = 1e-2      # melt-fraction window width over which to smooth material properties

# Outgassing - physics table
[outgas]
    fO2_shift_IW    = 4         # log10(Î”IW), atmosphere/interior boundary oxidation state
    module = "calliope"         # Which outgassing module to use


# Volatile delivery - physics table
[delivery]
    initial = 'elements'        # "elements" | "volatiles"

    module = "none"

    # Set initial volatile inventory by planetary element abundances
    [delivery.elements]
        H_oceans    = 8.0       # Hydrogen inventory in units of equivalent Earth oceans
        # H_ppmw      = 0.0     # Hydrogen inventory in ppmw relative to mantle mass

        CH_ratio    = 1.0       # C/H mass ratio in mantle/atmosphere system
        # C_ppmw      = 0.0       # Carbon inventory in ppmw relative to mantle mass

        # NH_ratio    = 0.0       # N/H mass ratio in mantle/atmosphere system
        N_ppmw      = 2.01      # Nitrogen inventory in ppmw relative to mantle mass

        # SH_ratio    = 0.0       # S/H mass ratio in mantle/atmosphere system
        S_ppmw      = 235.0     # Sulfur inventory in ppmw relative to mantle mass

# Calculate simulated observations
[observe]
    synthesis = "none"

[atmos_chem]
    module = "none"
