# Configuration file used for CHILI Model Intercomparison Project

version = "2.0"

# Parameters
[params]
    # output files
    [params.out]
        path        = "chili_protocol_tr1b"
        logging     = "INFO"
        plot_mod    = 20      # Plotting frequency, 0: wait until completion | n: every n iterations | none: do not plot
        plot_fmt    = "png"  # Plotting image file format, "png" or "pdf" recommended
        write_mod   = 1      # Write CSV frequency, 0: wait until completion | n: every n iterations
        archive_mod = 'none'      # Archive frequency, 0: wait until completion | n: every n iterations | none: do not archive
        remove_sf   = true    # Remove SOCRATES spectral file when simulation ends.

    # time-stepping
    [params.dt]
        minimum      = 1e4    # absolute minimum time-step [years]
        minimum_rel  = 1e-5   # relative minimum time-step [dimensionless]
        maximum      = 1e7    # maximum time-step [yr]
        initial      = 3e1    # inital step size [yr]
        starspec     = 1e7    # interval to re-calculate the stellar spectrum [yr]
        starinst     = 1e1    # interval to re-calculate the instellation [yr]
        method       = "adaptive"  # proportional | adaptive | maximum

        [params.dt.proportional]
            propconst    = 52.0   # Proportionality constant

        [params.dt.adaptive]
            atol         = 0.02   # Step size atol
            rtol         = 0.09   # Step size rtol

    # Termination criteria
    #     Set enabled=true/false in each section to enable/disable that termination criterion
    [params.stop]

        # Require criteria to be satisfied twice before model will exit?
        strict = false

        # required number of iterations
        [params.stop.iters]
            enabled = true
            minimum = 5
            maximum = 9000

        # required time constraints
        [params.stop.time]
            enabled = true
            minimum = 1.0e3      # model will certainly run to t > minimum [yr]
            maximum = 5.0e+9   # model will terminate when t > maximum [yr]

        # solidification
        [params.stop.solid]
            enabled  = true
            phi_crit = 0.03      # non-dim., model will terminate when global melt fraction < phi_crit

        # radiative equilibrium
        [params.stop.radeqm]
            enabled = false
            atol    = 0.2        # absolute tolerance [W m-2]
            rtol    = 1e-3       # relative tolerance

        [params.stop.escape]
            enabled = false
            p_stop  = 5.0        # Stop surface pressure is less than this value

        # disintegration
        [params.stop.disint]
            enabled   = false

            roche_enabled = true
            offset_roche  = 0 # correction to calculated Roche limit [m]

            spin_enabled  = true
            offset_spin   = 0 # correction to calculated Breakup period [s]


# ----------------------------------------------------
# Star
[star]

    # Physical parameters
    mass    = 0.10       # stellar mass [M_sun]
    age_ini = 0.050     # model initialisation age [Gyr]

    module  = "mors"

    [star.mors]
        rot_pcntle  = 50.0      # rotation percentile
        rot_period  = "none"    # rotation period [days]
        tracks      = "spada"   # evolution tracks: spada | baraffe
        age_now     = 7.6     # current age of star [Gyr]
        spec        = "stellar_spectra/Named/trappist-1.txt" # path to stellar spectrum file

    [star.dummy]
        radius           = 1.0      # Constant stellar radius [R_sun]
        calculate_radius = false    # Calculate star radius using scaling from Teff?
        Teff             = 5772.0   # Star's brightness temperature [K]

# Orbital system
[orbit]
    semimajoraxis = 0.01154        # initial semi-major axis of planet's orbit [AU]
    eccentricity = 0.0          # initial eccentricity of planet's orbit [dimensionless]
    zenith_angle = 48.19        # characteristic zenith angle [degrees]
    s0_factor = 0.375           # instellation scale factor [dimensionless]

    evolve  = false             # whether to evolve the SMaxis and eccentricity
    module  = "lovepy"          # module used to calculate tidal heating

    axial_period = "none"       # planet's initial day length [hours]; will use orbital period if 'none'
    satellite = false           # include satellite (moon)?
    mass_sat = 7.347e+22        # mass of satellite [kg]
    semimajoraxis_sat = 3e8     # initial SMA of satellite's orbit [m]

    [orbit.dummy]
        H_tide  = 1e-7      # Fixed tidal power density [W kg-1]
        Phi_tide = "<0.3"   # Tidal heating applied when inequality locally satisfied
        Imk2    = 0.0       # Fixed imaginary part of k2 love number, cannot be positive

    [orbit.lovepy]
        visc_thresh = 1e9   # Minimum viscosity required for heating [Pa s]

# Planetary structure - physics table
[struct]
    mass_tot     = 1.0          # M_earth
    radius_int   = "none"       # R_earth
    corefrac     = 0.55         # non-dim., radius fraction
    core_density = 10738.33     # Core density [kg m-3]
    core_heatcap = 880.0        # Core specific heat capacity [J K-1 kg-1]
    module       = "self"       # self | zalmoxis

# Atmosphere - physics table
[atmos_clim]
    prevent_warming = false      # do not allow the planet to heat up
    surface_d       = 0.01      # m, conductive skin thickness
    surface_k       = 2.0       # W m-1 K-1, conductive skin thermal conductivity
    cloud_enabled   = false     # enable water cloud radiative effects
    cloud_alpha     = 0.0       # condensate retention fraction (1 -> fully retained)
    surf_state      = "fixed"   # surface scheme: "mixed_layer" | "fixed" | "skin"
    surf_greyalbedo = 0.1       # surface grey albedo
    albedo_pl       = 0.1   	# Bond albedo (scattering)
    rayleigh        = false     # enable rayleigh scattering
    tmp_minimum     = 0.5       # temperature floor on solver
    tmp_maximum     = 5000.0    # temperature ceiling on solver

    module  = "agni"            # Which atmosphere module to use

    [atmos_clim.agni]
        p_top           = 1.0e-5        # bar, top of atmosphere grid pressure
        p_obs           = 0.02          # bar, level probed in transmission
        spectral_group  = "Dayspring"   # which gas opacities to include
        spectral_bands  = "48"          # how many spectral bands?
        num_levels      = 40            # Number of atmospheric grid levels
        chemistry       = "eq"        # "none" | "eq"
        surf_material   = "greybody"    # surface material file for scattering
        solve_energy    = true          # solve for energy-conserving atmosphere profile
        solution_atol   = 0.1           # solver absolute tolerance
        solution_rtol   = 0.1          # solver relative tolerance
        overlap_method  = "ee"          # gas overlap method
        condensation    = false         # volatile condensation
        latent_heat     = false         # include latent heat release by phase change?
        real_gas        = false         # use real-gas equations of state
        psurf_thresh    = 0.1           # bar, surface pressure where we switch to 'transparent' mode
        dx_max          = 10.0          # maximum temperature step [kelvin] allowed by solver
        max_steps       = 70            # max steps allowed by solver during each iteration
        perturb_all     = true          # updated entire jacobian each step?
        mlt_criterion   = "l"           # MLT convection stability criterion; (l)edoux or (s)chwarzschild
        fastchem_floor  = 100.0

    [atmos_clim.dummy]
        gamma           = 0.01          # atmosphere opacity between 0 and 1
        height_factor   = 3.0           # observed height is this times the scale height

# Volatile escape - physics table
[escape]

    module     = "zephyrus"         # Which escape module to use
    reservoir  = "outgas"           # Reservoir that sets escaping gas composition

    [escape.zephyrus]
        Pxuv        = 5e-5          # Pressure at which XUV radiation become opaque in the planetary atmosphere [bar]
        efficiency  = 0.1           # Escape efficiency factor
        tidal       = true         # Tidal contribution enabled

    [escape.dummy]
        rate        = 0.0           # Bulk unfractionated escape rate [kg s-1]

# Interior - physics table
[interior]
    grain_size      = 0.1           # crystal settling grain size [m]
    F_initial       = 1e3           # Initial heat flux guess [W m-2]
    radiogenic_heat = true         # enable radiogenic heat production
    tidal_heat      = true         # enable tidal heat production
    rheo_phi_loc    = 0.6           # Centre of rheological transition
    rheo_phi_wid    = 0.2           # Width of rheological transition

    module = "spider"       # Which interior module to use

    [interior.spider]
        num_levels      = 140       # Number of SPIDER grid levels
        mixing_length   = 2         # Mixing length parameterization
        tolerance       = 1.0e-8    # absolute solver tolerance
        tolerance_rel   = 1.0e-8    # relative solver tolerance
        solver_type     = "bdf"     # SUNDIALS solver method
        tsurf_atol      = 10.0      # tsurf_poststep_change
        tsurf_rtol      = 0.02      # tsurf_poststep_change_frac
        ini_entropy     = 3000.0    # Surface entropy conditions [J K-1 kg-1]
        ini_dsdr        = -4.698e-6 # Interior entropy gradient [J K-1 kg-1 m-1]

    [interior.dummy]
        ini_tmagma  = 3300.0    # Initial magma surface temperature [K]
        tmagma_atol = 30.0      # Max absolute Tsurf change in each step
        tmagma_rtol = 0.05      # Max relative Tsurf change in each step
        mantle_tliq = 2700.0    # Liquidus temperature
        mantle_tsol = 1700.0    # Solidus temperature
        mantle_rho  = 4550.0    # Mantle density [kg m-3]
        mantle_cp   = 1792.0    # Mantle heat capacity [J K-1 kg-1]
        H_ratio     = 0.0       # Radiogenic heating [W/kg]

# Outgassing - physics table
[outgas]
    fO2_shift_IW    = 4         # atmosphere/interior boundary oxidation state [log10(Î”IW)]

    module = "calliope"         # Which outgassing module to use

    [outgas.calliope]
        include_H2O  = true     # Include H2O compound
        include_CO2  = true     # Include CO2 compound
        include_N2   = true     # Include N2 compound
        include_S2   = true     # Include S2 compound
        include_SO2  = false     # Include SO2 compound
        include_H2S  = false     # Include H2S compound
        include_NH3  = false     # Include NH3 compound
        include_H2   = false     # Include H2 compound
        include_CH4  = false     # Include CH4 compound
        include_CO   = false     # Include CO compound
        T_floor      = 700.0    # Temperature floor applied to outgassing calculation [K].
        rtol         = 0.0001   # Relative mass tolerance
        xtol         = 1e-06    # Absolute mass tolerance
        solubility   = true     # Enable solubility?

    [outgas.atmodeller]
        some_parameter = "some_value"

# Volatile delivery - physics table
[delivery]

    # Radionuclide parameters
    radio_tref = 4.55   # Reference age for concentrations [Gyr]
    radio_K    = 310.0  # ppmw of potassium (all isotopes)
    radio_U    = 0.031  # ppmw of uranium (all isotopes)
    radio_Th   = 0.124  # ppmw of thorium (all isotopes)

    # Which initial inventory to use?
    initial = 'elements'        # 'elements' | 'volatiles'

    # No module for accretion as of yet
    module = "none"

    # Set initial volatile inventory by planetary element abundances if [initial = 'elements']
    [delivery.elements]
        C_kg   = 5.458e20       # Carbon inventory
        H_kg   = 1.119e20       # Hydrogen inventory
        N_kg   = 0.0       # Nitrogen inventory
        S_kg   = 0.0       # Sulfur inventory


# Atmospheric chemistry postprocessing
[atmos_chem]

    module  = "vulcan"          # Atmospheric chemistry module
    when    = "manually"        # When to run chemistry (manually, offline, online)

    # Physics flags
    photo_on        = true      # Enable photochemistry
    Kzz_on          = true      # Enable eddy diffusion
    Kzz_const       = "none"    # Constant eddy diffusion coefficient (none => use profile)
    moldiff_on      = true      # Enable molecular diffusion in the atmosphere
    updraft_const   = 0.0       # Set constant updraft velocity

    # Vulcan-specific atmospheric chemistry parameters
    [atmos_chem.vulcan]
        clip_fl     = 1e-20     # Floor on stellar spectrum [erg s-1 cm-2 nm-1]
        clip_vmr    = 1e-10     # Neglect species with vmr < clip_vmr
        make_funs   = true      # Generate reaction network functions
        ini_mix     = "profile" # Initial mixing ratios (profile, outgas)
        fix_surf    = false     # Fixed surface mixing ratios
        network     = "SNCHO"   # Class of chemical network to use (CHO, NCHO, SNCHO)
        save_frames = true      # Plot frames during iterations
        yconv_cri   = 0.05      # Convergence criterion, value of mixing ratios
        slope_cri   = 0.0001    # Convergence criterion, rate of change of mixing ratios

# Calculate simulated observations
[observe]

    # Module with which to calculate the synthetic observables
    synthesis = "none"

    [observe.platon]
        downsample = 8      # Factor to downsample opacities
        clip_vmr   = 1e-8   # Minimum VMR for a species to be included
