# Config file for running a grid of forward models

# Path to output folder where grid will be saved (relative to PROTEUS output folder)
output = "scratch/escape_on_off_janus_agni_1Msun_solid/"

# Make `output` a symbolic link to this absolute location. To disable: set to empty string.
symlink = ""

# Path to base (reference) config file relative to PROTEUS root folder
ref_config = "input/demos/escape_comparison.toml"

# Use SLURM?
use_slurm = true

# Execution limits
max_jobs = 5       # maximum number of concurrent tasks (e.g. 500 on Habrok)
max_days = 5        # maximum number of days to run (e.g. 1)
max_mem  = 3        # maximum memory per CPU in GB (e.g. 3)

# Now define grid axes...
#    Each axis must be a new section (table) in this file.
#    Each table corresponds to the name of the parameter to be varied.
#    Each table name must be written in double quotes.
#    See examples below

# Escape module set directly
["escape.module"]
    method = "direct"
    values = ['none', 'zephyrus']

# Atmosphere module set directly
["atmos_clim.module"]
    method = "direct"
    values = ['janus', 'agni']
