# Config file for running a grid of forward models

# Path to output folder where grid will be saved (relative to PROTEUS output folder)
output = "grid_demo/"

# Make `output` a symbolic link to this absolute location. To disable: set to empty string.
symlink = ""

# Path to base (reference) config file relative to PROTEUS root folder
ref_config = "input/all_options.toml"

# Use SLURM?
use_slurm = false

# Execution limits
max_jobs = 10       # maximum number of concurrent tasks (e.g. 500 on Habrok)
max_days = 1        # maximum number of days to run (e.g. 1)
max_mem  = 3        # maximum memory per CPU in GB (e.g. 3)

# Now define grid axes...
#    Each axis must be a new section (table) in this file.
#    Each table corresponds to the name of the parameter to be varied.
#    Each table name must be written in double quotes.
#    See examples below

["outgas.fO2_shift_IW"]
    method = "direct"
    values = [-4, -2, 0, 2,4]

["delivery.elements.H_oceans"]
    method = "linspace"
    start    = 1.0
    stop     = 10.0
    count     = 5

["delivery.elements.CH_ratio"]
    method = "logspace"
    start    = 0.1
    stop     = 10.0
    count     = 3


["delivery.elements.NH_ratio"]
    method = "logspace"
    start    = 0.05
    stop     = 5.0
    count     = 3


["delivery.elements.SH_ratio"]
    method = "logspace"
    start    = 0.2
    stop     = 20
    count     = 3

# Planet mass set directly
#["struct.mass_tot"]
#    method = "direct"
#    values = [0.7, 1.0, 2.0, 3.0]

# Hydrogen inventory set by arange
#["delivery.elements.H_ppmw"]
#    method = "arange"
#    start    = 5000
#    stop     = 20000
#    step     = 5000

# Mantle redox state set directly
# ["outgas.fO2_shift_IW"]
#     method = "direct"
#     values = [-3, -2, -1]

# Planet bulk S/H ratio set directly
# ["delivery.elements.SH_ratio"]
#     method = "direct"
#     values = [2, 4, 6, 8]

# Escape efficiency set by arange
# ["escape.zephyrus.efficiency"]
#     method   = "arange"
#     start    = 0.0
#     stop     = 0.25
#     step     = 0.05

# Core radius fraction set by linspace
# ["struct.corefrac"]
#     method = "linspace"
#     start  = 0.35
#     stop   = 0.95
#     count  = 3

# Orbital eccentricity set by logspace
# ["orbit.eccentricity"]
#     method = "logspace"
#     start  = 0.001
#     stop   = 0.15
#     count  = 25


# Spectral bands set directly
# ["atmos_clim.agni.spectral_bands"]
#     method = "direct"
#     values = ["16", "48", "256"]
