# Config file for inference scheme

# Set seed for reproducibility
seed = 1

# Path to output folder where inference will be saved (relative to PROTEUS output folder)
output = "infer_toy/BO/"

# Path to base (reference) config file relative to PROTEUS root folder
ref_config = "input/demos/dummy.toml"

# Method for initialising the inference scheme (one of these must be 'none')
init_samps = 10        # Number of random samples if starting from scratch.
init_grid  = 'none' # grid_demo/'   # Path pre-computed grid (relative to PROTEUS output folder)

# Parameters for Bayesian optimisation
n_workers  = 6        # Number of parallel workers
kernel     = "MAT3/2"    # Kernel type for GP, "RBF" | "MAT1/2" | "MAT3/2" | "MAT5/2"
acqf       = "LogEI"  # Acquisition function, "UCB" | "LogEI" | "E-LogEI"
n_steps    = 50       # Total number of evaluations (i.e. BO steps)

# Parameters to optimize (with bounds)
[parameters]
"struct.mass_tot" = [0.7, 3.0]
"struct.corefrac" = [0.3, 0.9]
# "delivery.elements.H_ppmw" = [1e3, 2e4]
# "outgas.fO2_shift_IW" = [-3.0, 5.0]
# "escape.dummy.rate" = [1e5, 1e7]

# Target observables to match by optimisation
[observables]
"R_obs" = 7965615.42040000017732382
# "H2O_vmr" = 0.69457002234999998
"P_surf" = 16333.19793399999980466
